#!/bin/bash --login

#SBATCH --job-name=reserved
#SBATCH --nodes=1
#SBATCH --tasks-per-node=128
#SBATCH --cpus-per-task=1
#SBATCH --time=0:20:0
#SBATCH --account=e05-discov-cat
#SBATCH --partition=standard
#SBATCH --reservation=e05-discov-cat_1620660
#SBATCH --qos=reservation

module load epcc-setup-env
module load cray-python

export SLURM_CPU_FREQ_REQ=2250000

python_input=optimise.py

export TEMP_DIRECTORY="/mnt/lustre/a2fs-nvme/work/e05/e05/$USER/$SLURM_JOB_ID"
export HOME_DIRECTORY=$PWD
mkdir $TEMP_DIRECTORY

rsync -av . $TEMP_DIRECTORY
cd $TEMP_DIRECTORY

# Run the Python job
export output=test.log.$SLURM_JOB_ID
time python -u $python_input > $output 

# Cleanup task
echo "Starting cleanup..."

rsync -av $TEMP_DIRECTORY $HOME_DIRECTORY --exclude="*.tmp*" --exclude="*.bas*" --exclude="$output" --exclude="slurm-$SLURM_JOB_ID.out"
rm $TEMP_DIRECTORY -r

echo "Cleanup completed."
